# Generated by Django 4.0.3 on 2022-03-31 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
